
description: Pixart PMW3610 trackball sensor driver (ZMK Custom Auto-Layer)
compatible: "pixart,pmw3610"

properties:
  input-processors:
    type: phandle-array
    description: Input processor nodes associated with this input device.
    required: false
